# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'charSheet.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CharacterSheet(object):
    def setupUi(self, CharacterSheet):
        CharacterSheet.setObjectName("CharacterSheet")
        CharacterSheet.resize(1276, 847)
        CharacterSheet.setMinimumSize(QtCore.QSize(0, 0))
        CharacterSheet.setMaximumSize(QtCore.QSize(999999, 999999))
        self.nameBox = QtWidgets.QGroupBox(CharacterSheet)
        self.nameBox.setGeometry(QtCore.QRect(20, 10, 241, 51))
        self.nameBox.setObjectName("nameBox")
        self.nameLbl = QtWidgets.QLabel(self.nameBox)
        self.nameLbl.setGeometry(QtCore.QRect(16, 20, 211, 20))
        self.nameLbl.setObjectName("nameLbl")
        self.line = QtWidgets.QFrame(CharacterSheet)
        self.line.setGeometry(QtCore.QRect(-70, 60, 1431, 20))
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.streBox = QtWidgets.QGroupBox(CharacterSheet)
        self.streBox.setGeometry(QtCore.QRect(20, 240, 91, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.streBox.setFont(font)
        self.streBox.setObjectName("streBox")
        self.streLbl = QtWidgets.QLabel(self.streBox)
        self.streLbl.setGeometry(QtCore.QRect(14, 20, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.streLbl.setFont(font)
        self.streLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.streLbl.setObjectName("streLbl")
        self.line_2 = QtWidgets.QFrame(CharacterSheet)
        self.line_2.setGeometry(QtCore.QRect(330, 66, 16, 851))
        self.line_2.setLineWidth(4)
        self.line_2.setMidLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.dextBox = QtWidgets.QGroupBox(CharacterSheet)
        self.dextBox.setGeometry(QtCore.QRect(20, 330, 91, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dextBox.setFont(font)
        self.dextBox.setObjectName("dextBox")
        self.dextLbl = QtWidgets.QLabel(self.dextBox)
        self.dextLbl.setGeometry(QtCore.QRect(10, 20, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dextLbl.setFont(font)
        self.dextLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.dextLbl.setObjectName("dextLbl")
        self.consBox = QtWidgets.QGroupBox(CharacterSheet)
        self.consBox.setGeometry(QtCore.QRect(20, 420, 91, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.consBox.setFont(font)
        self.consBox.setObjectName("consBox")
        self.consLbl = QtWidgets.QLabel(self.consBox)
        self.consLbl.setGeometry(QtCore.QRect(10, 20, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.consLbl.setFont(font)
        self.consLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.consLbl.setObjectName("consLbl")
        self.inteBox = QtWidgets.QGroupBox(CharacterSheet)
        self.inteBox.setGeometry(QtCore.QRect(20, 510, 91, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.inteBox.setFont(font)
        self.inteBox.setObjectName("inteBox")
        self.inteLbl = QtWidgets.QLabel(self.inteBox)
        self.inteLbl.setGeometry(QtCore.QRect(10, 20, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.inteLbl.setFont(font)
        self.inteLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.inteLbl.setObjectName("inteLbl")
        self.wisdBox = QtWidgets.QGroupBox(CharacterSheet)
        self.wisdBox.setGeometry(QtCore.QRect(20, 600, 91, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.wisdBox.setFont(font)
        self.wisdBox.setObjectName("wisdBox")
        self.wisdLbl = QtWidgets.QLabel(self.wisdBox)
        self.wisdLbl.setGeometry(QtCore.QRect(10, 20, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.wisdLbl.setFont(font)
        self.wisdLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.wisdLbl.setObjectName("wisdLbl")
        self.charBox = QtWidgets.QGroupBox(CharacterSheet)
        self.charBox.setGeometry(QtCore.QRect(20, 690, 91, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.charBox.setFont(font)
        self.charBox.setObjectName("charBox")
        self.charLbl = QtWidgets.QLabel(self.charBox)
        self.charLbl.setGeometry(QtCore.QRect(10, 20, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.charLbl.setFont(font)
        self.charLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.charLbl.setObjectName("charLbl")
        self.profBox = QtWidgets.QGroupBox(CharacterSheet)
        self.profBox.setGeometry(QtCore.QRect(20, 80, 241, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.profBox.setFont(font)
        self.profBox.setObjectName("profBox")
        self.label_2 = QtWidgets.QLabel(self.profBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.inspBox = QtWidgets.QGroupBox(CharacterSheet)
        self.inspBox.setGeometry(QtCore.QRect(20, 160, 241, 61))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.inspBox.setFont(font)
        self.inspBox.setObjectName("inspBox")
        self.label = QtWidgets.QLabel(self.inspBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(CharacterSheet)
        self.groupBox.setGeometry(QtCore.QRect(290, 10, 141, 51))
        self.groupBox.setObjectName("groupBox")
        self.classLbl = QtWidgets.QLabel(self.groupBox)
        self.classLbl.setGeometry(QtCore.QRect(10, 20, 121, 21))
        self.classLbl.setObjectName("classLbl")
        self.groupBox_2 = QtWidgets.QGroupBox(CharacterSheet)
        self.groupBox_2.setGeometry(QtCore.QRect(460, 10, 241, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.raceLbl = QtWidgets.QLabel(self.groupBox_2)
        self.raceLbl.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.raceLbl.setObjectName("raceLbl")
        self.backgroundLbl = QtWidgets.QLabel(self.groupBox_2)
        self.backgroundLbl.setGeometry(QtCore.QRect(130, 20, 101, 21))
        self.backgroundLbl.setObjectName("backgroundLbl")
        self.groupBox_3 = QtWidgets.QGroupBox(CharacterSheet)
        self.groupBox_3.setGeometry(QtCore.QRect(720, 10, 171, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.alignLbl = QtWidgets.QLabel(self.groupBox_3)
        self.alignLbl.setGeometry(QtCore.QRect(10, 20, 151, 21))
        self.alignLbl.setObjectName("alignLbl")
        self.groupBox_4 = QtWidgets.QGroupBox(CharacterSheet)
        self.groupBox_4.setGeometry(QtCore.QRect(350, 80, 371, 471))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 30, 91, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.armorLbl = QtWidgets.QLabel(self.groupBox_5)
        self.armorLbl.setGeometry(QtCore.QRect(10, 20, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.armorLbl.setFont(font)
        self.armorLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.armorLbl.setObjectName("armorLbl")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_6.setGeometry(QtCore.QRect(270, 30, 91, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.initiaiveLbl = QtWidgets.QLabel(self.groupBox_6)
        self.initiaiveLbl.setGeometry(QtCore.QRect(10, 20, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.initiaiveLbl.setFont(font)
        self.initiaiveLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.initiaiveLbl.setObjectName("initiaiveLbl")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_7.setGeometry(QtCore.QRect(120, 30, 131, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.maxHPLbl = QtWidgets.QLabel(self.groupBox_7)
        self.maxHPLbl.setGeometry(QtCore.QRect(20, 20, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.maxHPLbl.setFont(font)
        self.maxHPLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.maxHPLbl.setObjectName("maxHPLbl")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 110, 351, 80))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.hpLbl = QtWidgets.QLabel(self.groupBox_8)
        self.hpLbl.setGeometry(QtCore.QRect(94, 30, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.hpLbl.setFont(font)
        self.hpLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.hpLbl.setObjectName("hpLbl")
        self.hpMinusBtn = QtWidgets.QPushButton(self.groupBox_8)
        self.hpMinusBtn.setGeometry(QtCore.QRect(20, 30, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.hpMinusBtn.setFont(font)
        self.hpMinusBtn.setObjectName("hpMinusBtn")
        self.hpPlusBtn = QtWidgets.QPushButton(self.groupBox_8)
        self.hpPlusBtn.setGeometry(QtCore.QRect(280, 30, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.hpPlusBtn.setFont(font)
        self.hpPlusBtn.setObjectName("hpPlusBtn")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 200, 91, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.hitLbl = QtWidgets.QLabel(self.groupBox_9)
        self.hitLbl.setGeometry(QtCore.QRect(10, 20, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.hitLbl.setFont(font)
        self.hitLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.hitLbl.setObjectName("hitLbl")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_10.setGeometry(QtCore.QRect(120, 200, 131, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.deathLbl = QtWidgets.QLabel(self.groupBox_10)
        self.deathLbl.setGeometry(QtCore.QRect(10, 20, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.deathLbl.setFont(font)
        self.deathLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.deathLbl.setObjectName("deathLbl")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_11.setGeometry(QtCore.QRect(270, 200, 91, 80))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.speedLbl = QtWidgets.QLabel(self.groupBox_11)
        self.speedLbl.setGeometry(QtCore.QRect(10, 20, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.speedLbl.setFont(font)
        self.speedLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.speedLbl.setObjectName("speedLbl")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 290, 351, 171))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 30, 161, 131))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.weapon1Lbl = QtWidgets.QLabel(self.groupBox_13)
        self.weapon1Lbl.setGeometry(QtCore.QRect(10, 25, 141, 21))
        self.weapon1Lbl.setObjectName("weapon1Lbl")
        self.weapon2Lbl = QtWidgets.QLabel(self.groupBox_13)
        self.weapon2Lbl.setGeometry(QtCore.QRect(10, 60, 141, 21))
        self.weapon2Lbl.setObjectName("weapon2Lbl")
        self.weapon3Lbl = QtWidgets.QLabel(self.groupBox_13)
        self.weapon3Lbl.setGeometry(QtCore.QRect(10, 100, 141, 21))
        self.weapon3Lbl.setObjectName("weapon3Lbl")
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_14.setGeometry(QtCore.QRect(180, 30, 61, 131))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.bonus1Lbl = QtWidgets.QLabel(self.groupBox_14)
        self.bonus1Lbl.setGeometry(QtCore.QRect(10, 25, 41, 21))
        self.bonus1Lbl.setObjectName("bonus1Lbl")
        self.bonus2Lbl = QtWidgets.QLabel(self.groupBox_14)
        self.bonus2Lbl.setGeometry(QtCore.QRect(10, 60, 41, 21))
        self.bonus2Lbl.setObjectName("bonus2Lbl")
        self.bonus3Lbl = QtWidgets.QLabel(self.groupBox_14)
        self.bonus3Lbl.setGeometry(QtCore.QRect(10, 100, 41, 21))
        self.bonus3Lbl.setObjectName("bonus3Lbl")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_12)
        self.groupBox_15.setGeometry(QtCore.QRect(250, 30, 91, 131))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName("groupBox_15")
        self.damage1Lbl = QtWidgets.QLabel(self.groupBox_15)
        self.damage1Lbl.setGeometry(QtCore.QRect(10, 25, 71, 21))
        self.damage1Lbl.setObjectName("damage1Lbl")
        self.damage2Lbl = QtWidgets.QLabel(self.groupBox_15)
        self.damage2Lbl.setGeometry(QtCore.QRect(10, 60, 71, 21))
        self.damage2Lbl.setObjectName("damage2Lbl")
        self.damage3Lbl = QtWidgets.QLabel(self.groupBox_15)
        self.damage3Lbl.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.damage3Lbl.setObjectName("damage3Lbl")
        self.groupBox_16 = QtWidgets.QGroupBox(CharacterSheet)
        self.groupBox_16.setGeometry(QtCore.QRect(350, 550, 371, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setObjectName("groupBox_16")
        self.proficienciesLbl = QtWidgets.QLabel(self.groupBox_16)
        self.proficienciesLbl.setGeometry(QtCore.QRect(10, 25, 351, 215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.proficienciesLbl.setFont(font)
        self.proficienciesLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.proficienciesLbl.setObjectName("proficienciesLbl")
        self.groupBox_17 = QtWidgets.QGroupBox(CharacterSheet)
        self.groupBox_17.setGeometry(QtCore.QRect(730, 80, 531, 281))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_17)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 511, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_20 = QtWidgets.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_20.setFont(font)
        self.groupBox_20.setObjectName("groupBox_20")
        self.personalityLbl = QtWidgets.QLabel(self.groupBox_20)
        self.personalityLbl.setGeometry(QtCore.QRect(10, 25, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.personalityLbl.setFont(font)
        self.personalityLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.personalityLbl.setObjectName("personalityLbl")
        self.gridLayout.addWidget(self.groupBox_20, 0, 0, 1, 1)
        self.groupBox_21 = QtWidgets.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_21.setFont(font)
        self.groupBox_21.setObjectName("groupBox_21")
        self.idealsLbl = QtWidgets.QLabel(self.groupBox_21)
        self.idealsLbl.setGeometry(QtCore.QRect(10, 20, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.idealsLbl.setFont(font)
        self.idealsLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.idealsLbl.setObjectName("idealsLbl")
        self.gridLayout.addWidget(self.groupBox_21, 0, 1, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_19.setFont(font)
        self.groupBox_19.setObjectName("groupBox_19")
        self.flawsLbl = QtWidgets.QLabel(self.groupBox_19)
        self.flawsLbl.setGeometry(QtCore.QRect(10, 20, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.flawsLbl.setFont(font)
        self.flawsLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.flawsLbl.setObjectName("flawsLbl")
        self.gridLayout.addWidget(self.groupBox_19, 1, 1, 1, 1)
        self.groupBox_18 = QtWidgets.QGroupBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_18.setFont(font)
        self.groupBox_18.setObjectName("groupBox_18")
        self.bondsLbl = QtWidgets.QLabel(self.groupBox_18)
        self.bondsLbl.setGeometry(QtCore.QRect(10, 20, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.bondsLbl.setFont(font)
        self.bondsLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.bondsLbl.setObjectName("bondsLbl")
        self.gridLayout.addWidget(self.groupBox_18, 1, 0, 1, 1)
        self.spellBtn = QtWidgets.QPushButton(CharacterSheet)
        self.spellBtn.setGeometry(QtCore.QRect(910, 17, 81, 41))
        self.spellBtn.setObjectName("spellBtn")
        self.invBtn = QtWidgets.QPushButton(CharacterSheet)
        self.invBtn.setGeometry(QtCore.QRect(1000, 17, 81, 41))
        self.invBtn.setObjectName("invBtn")
        self.editBtn = QtWidgets.QPushButton(CharacterSheet)
        self.editBtn.setGeometry(QtCore.QRect(1090, 17, 81, 41))
        self.editBtn.setObjectName("editBtn")
        self.groupBox_22 = QtWidgets.QGroupBox(CharacterSheet)
        self.groupBox_22.setGeometry(QtCore.QRect(730, 370, 531, 471))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_22.setFont(font)
        self.groupBox_22.setObjectName("groupBox_22")
        self.groupBox_23 = QtWidgets.QGroupBox(self.groupBox_22)
        self.groupBox_23.setGeometry(QtCore.QRect(10, 29, 511, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_23.setFont(font)
        self.groupBox_23.setObjectName("groupBox_23")
        self.featsLbl = QtWidgets.QLabel(self.groupBox_23)
        self.featsLbl.setGeometry(QtCore.QRect(14, 25, 481, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.featsLbl.setFont(font)
        self.featsLbl.setObjectName("featsLbl")
        self.groupBox_24 = QtWidgets.QGroupBox(self.groupBox_22)
        self.groupBox_24.setGeometry(QtCore.QRect(10, 180, 511, 91))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_24.setFont(font)
        self.groupBox_24.setObjectName("groupBox_24")
        self.raceTraitsLbl = QtWidgets.QLabel(self.groupBox_24)
        self.raceTraitsLbl.setGeometry(QtCore.QRect(10, 20, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.raceTraitsLbl.setFont(font)
        self.raceTraitsLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.raceTraitsLbl.setObjectName("raceTraitsLbl")
        self.groupBox_25 = QtWidgets.QGroupBox(self.groupBox_22)
        self.groupBox_25.setGeometry(QtCore.QRect(10, 100, 511, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_25.setFont(font)
        self.groupBox_25.setObjectName("groupBox_25")
        self.backgroundTraitsLbl = QtWidgets.QLabel(self.groupBox_25)
        self.backgroundTraitsLbl.setGeometry(QtCore.QRect(10, 24, 481, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.backgroundTraitsLbl.setFont(font)
        self.backgroundTraitsLbl.setObjectName("backgroundTraitsLbl")
        self.groupBox_26 = QtWidgets.QGroupBox(self.groupBox_22)
        self.groupBox_26.setGeometry(QtCore.QRect(10, 280, 511, 181))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_26.setFont(font)
        self.groupBox_26.setObjectName("groupBox_26")
        self.classTraitsLbl = QtWidgets.QLabel(self.groupBox_26)
        self.classTraitsLbl.setGeometry(QtCore.QRect(10, 20, 481, 131))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.classTraitsLbl.setFont(font)
        self.classTraitsLbl.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.classTraitsLbl.setObjectName("classTraitsLbl")
        self.groupBox_27 = QtWidgets.QGroupBox(CharacterSheet)
        self.groupBox_27.setGeometry(QtCore.QRect(20, 790, 241, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_27.setFont(font)
        self.groupBox_27.setObjectName("groupBox_27")
        self.pasWisdomLbl = QtWidgets.QLabel(self.groupBox_27)
        self.pasWisdomLbl.setGeometry(QtCore.QRect(10, 20, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pasWisdomLbl.setFont(font)
        self.pasWisdomLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.pasWisdomLbl.setObjectName("pasWisdomLbl")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(CharacterSheet)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(130, 240, 181, 547))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.d = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.d.setFont(font)
        self.d.setAlignment(QtCore.Qt.AlignCenter)
        self.d.setObjectName("d")
        self.gridLayout_2.addWidget(self.d, 3, 0, 1, 1)
        self.f = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.f.setFont(font)
        self.f.setAlignment(QtCore.Qt.AlignCenter)
        self.f.setObjectName("f")
        self.gridLayout_2.addWidget(self.f, 5, 0, 1, 1)
        self.b = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b.setFont(font)
        self.b.setAlignment(QtCore.Qt.AlignCenter)
        self.b.setObjectName("b")
        self.gridLayout_2.addWidget(self.b, 1, 0, 1, 1)
        self.h = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.h.setFont(font)
        self.h.setAlignment(QtCore.Qt.AlignCenter)
        self.h.setObjectName("h")
        self.gridLayout_2.addWidget(self.h, 7, 0, 1, 1)
        self.c = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.c.setFont(font)
        self.c.setAlignment(QtCore.Qt.AlignCenter)
        self.c.setObjectName("c")
        self.gridLayout_2.addWidget(self.c, 2, 0, 1, 1)
        self.j = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.j.setFont(font)
        self.j.setAlignment(QtCore.Qt.AlignCenter)
        self.j.setObjectName("j")
        self.gridLayout_2.addWidget(self.j, 9, 0, 1, 1)
        self.a = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.a.setFont(font)
        self.a.setAlignment(QtCore.Qt.AlignCenter)
        self.a.setObjectName("a")
        self.gridLayout_2.addWidget(self.a, 0, 0, 1, 1)
        self.e = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.e.setFont(font)
        self.e.setAlignment(QtCore.Qt.AlignCenter)
        self.e.setObjectName("e")
        self.gridLayout_2.addWidget(self.e, 4, 0, 1, 1)
        self.g = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.g.setFont(font)
        self.g.setAlignment(QtCore.Qt.AlignCenter)
        self.g.setObjectName("g")
        self.gridLayout_2.addWidget(self.g, 6, 0, 1, 1)
        self.i = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.i.setFont(font)
        self.i.setAlignment(QtCore.Qt.AlignCenter)
        self.i.setObjectName("i")
        self.gridLayout_2.addWidget(self.i, 8, 0, 1, 1)
        self.k = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.k.setFont(font)
        self.k.setAlignment(QtCore.Qt.AlignCenter)
        self.k.setObjectName("k")
        self.gridLayout_2.addWidget(self.k, 10, 0, 1, 1)
        self.l = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.l.setFont(font)
        self.l.setAlignment(QtCore.Qt.AlignCenter)
        self.l.setObjectName("l")
        self.gridLayout_2.addWidget(self.l, 11, 0, 1, 1)
        self.m = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.m.setFont(font)
        self.m.setAlignment(QtCore.Qt.AlignCenter)
        self.m.setObjectName("m")
        self.gridLayout_2.addWidget(self.m, 12, 0, 1, 1)
        self.p = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.p.setFont(font)
        self.p.setAlignment(QtCore.Qt.AlignCenter)
        self.p.setObjectName("p")
        self.gridLayout_2.addWidget(self.p, 15, 0, 1, 1)
        self.o = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.o.setFont(font)
        self.o.setAlignment(QtCore.Qt.AlignCenter)
        self.o.setObjectName("o")
        self.gridLayout_2.addWidget(self.o, 14, 0, 1, 1)
        self.n = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.n.setFont(font)
        self.n.setAlignment(QtCore.Qt.AlignCenter)
        self.n.setObjectName("n")
        self.gridLayout_2.addWidget(self.n, 13, 0, 1, 1)
        self.w = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.w.setFont(font)
        self.w.setAlignment(QtCore.Qt.AlignCenter)
        self.w.setObjectName("w")
        self.gridLayout_2.addWidget(self.w, 22, 0, 1, 1)
        self.x = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.x.setFont(font)
        self.x.setAlignment(QtCore.Qt.AlignCenter)
        self.x.setObjectName("x")
        self.gridLayout_2.addWidget(self.x, 23, 0, 1, 1)
        self.q = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.q.setFont(font)
        self.q.setAlignment(QtCore.Qt.AlignCenter)
        self.q.setObjectName("q")
        self.gridLayout_2.addWidget(self.q, 16, 0, 1, 1)
        self.v = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.v.setFont(font)
        self.v.setAlignment(QtCore.Qt.AlignCenter)
        self.v.setObjectName("v")
        self.gridLayout_2.addWidget(self.v, 21, 0, 1, 1)
        self.r = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.r.setFont(font)
        self.r.setAlignment(QtCore.Qt.AlignCenter)
        self.r.setObjectName("r")
        self.gridLayout_2.addWidget(self.r, 17, 0, 1, 1)
        self.s = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.s.setFont(font)
        self.s.setAlignment(QtCore.Qt.AlignCenter)
        self.s.setObjectName("s")
        self.gridLayout_2.addWidget(self.s, 18, 0, 1, 1)
        self.u = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.u.setFont(font)
        self.u.setAlignment(QtCore.Qt.AlignCenter)
        self.u.setObjectName("u")
        self.gridLayout_2.addWidget(self.u, 20, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 1, 1, 1)
        self.t = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.t.setFont(font)
        self.t.setAlignment(QtCore.Qt.AlignCenter)
        self.t.setObjectName("t")
        self.gridLayout_2.addWidget(self.t, 19, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 1, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_49.setObjectName("label_49")
        self.gridLayout_2.addWidget(self.label_49, 2, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_50.setObjectName("label_50")
        self.gridLayout_2.addWidget(self.label_50, 3, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_51.setObjectName("label_51")
        self.gridLayout_2.addWidget(self.label_51, 4, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_52.setObjectName("label_52")
        self.gridLayout_2.addWidget(self.label_52, 5, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_53.setObjectName("label_53")
        self.gridLayout_2.addWidget(self.label_53, 6, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_54.setObjectName("label_54")
        self.gridLayout_2.addWidget(self.label_54, 7, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_55.setObjectName("label_55")
        self.gridLayout_2.addWidget(self.label_55, 8, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_56.setObjectName("label_56")
        self.gridLayout_2.addWidget(self.label_56, 9, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_57.setObjectName("label_57")
        self.gridLayout_2.addWidget(self.label_57, 10, 1, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_58.setObjectName("label_58")
        self.gridLayout_2.addWidget(self.label_58, 11, 1, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_59.setObjectName("label_59")
        self.gridLayout_2.addWidget(self.label_59, 12, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_60.setObjectName("label_60")
        self.gridLayout_2.addWidget(self.label_60, 13, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_61.setObjectName("label_61")
        self.gridLayout_2.addWidget(self.label_61, 14, 1, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_62.setObjectName("label_62")
        self.gridLayout_2.addWidget(self.label_62, 15, 1, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_63.setObjectName("label_63")
        self.gridLayout_2.addWidget(self.label_63, 16, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_64.setObjectName("label_64")
        self.gridLayout_2.addWidget(self.label_64, 17, 1, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_65.setObjectName("label_65")
        self.gridLayout_2.addWidget(self.label_65, 18, 1, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_66.setObjectName("label_66")
        self.gridLayout_2.addWidget(self.label_66, 19, 1, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_67.setObjectName("label_67")
        self.gridLayout_2.addWidget(self.label_67, 20, 1, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_68.setObjectName("label_68")
        self.gridLayout_2.addWidget(self.label_68, 21, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_69.setObjectName("label_69")
        self.gridLayout_2.addWidget(self.label_69, 22, 1, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_70.setObjectName("label_70")
        self.gridLayout_2.addWidget(self.label_70, 23, 1, 1, 1)
        self.loadBtn = QtWidgets.QPushButton(CharacterSheet)
        self.loadBtn.setGeometry(QtCore.QRect(1180, 17, 81, 41))
        self.loadBtn.setObjectName("loadBtn")

        self.retranslateUi(CharacterSheet)
        QtCore.QMetaObject.connectSlotsByName(CharacterSheet)

    def retranslateUi(self, CharacterSheet):
        _translate = QtCore.QCoreApplication.translate
        CharacterSheet.setWindowTitle(_translate("CharacterSheet", "Dialog"))
        self.nameBox.setTitle(_translate("CharacterSheet", "Character Name"))
        self.nameLbl.setText(_translate("CharacterSheet", "Name"))
        self.streBox.setTitle(_translate("CharacterSheet", "Strength"))
        self.streLbl.setText(_translate("CharacterSheet", "0"))
        self.dextBox.setTitle(_translate("CharacterSheet", "Dexterity"))
        self.dextLbl.setText(_translate("CharacterSheet", "0"))
        self.consBox.setTitle(_translate("CharacterSheet", "Constitution"))
        self.consLbl.setText(_translate("CharacterSheet", "0"))
        self.inteBox.setTitle(_translate("CharacterSheet", "Intelligence"))
        self.inteLbl.setText(_translate("CharacterSheet", "0"))
        self.wisdBox.setTitle(_translate("CharacterSheet", "Wisdom"))
        self.wisdLbl.setText(_translate("CharacterSheet", "0"))
        self.charBox.setTitle(_translate("CharacterSheet", "Charisma"))
        self.charLbl.setText(_translate("CharacterSheet", "0"))
        self.profBox.setTitle(_translate("CharacterSheet", "Proficiency Bonus"))
        self.label_2.setText(_translate("CharacterSheet", "0"))
        self.inspBox.setTitle(_translate("CharacterSheet", "Insparation"))
        self.label.setText(_translate("CharacterSheet", "0"))
        self.groupBox.setTitle(_translate("CharacterSheet", "Class and Level"))
        self.classLbl.setText(_translate("CharacterSheet", "None"))
        self.groupBox_2.setTitle(_translate("CharacterSheet", "Race and Background"))
        self.raceLbl.setText(_translate("CharacterSheet", "None"))
        self.backgroundLbl.setText(_translate("CharacterSheet", "None"))
        self.groupBox_3.setTitle(_translate("CharacterSheet", "Alignment"))
        self.alignLbl.setText(_translate("CharacterSheet", "None"))
        self.groupBox_4.setTitle(_translate("CharacterSheet", "Combat"))
        self.groupBox_5.setTitle(_translate("CharacterSheet", "Armor Class"))
        self.armorLbl.setText(_translate("CharacterSheet", "0"))
        self.groupBox_6.setTitle(_translate("CharacterSheet", "Initiative"))
        self.initiaiveLbl.setText(_translate("CharacterSheet", "0"))
        self.groupBox_7.setTitle(_translate("CharacterSheet", "Hit Point Maximum"))
        self.maxHPLbl.setText(_translate("CharacterSheet", "0"))
        self.groupBox_8.setTitle(_translate("CharacterSheet", "Current Hit Points"))
        self.hpLbl.setText(_translate("CharacterSheet", "0"))
        self.hpMinusBtn.setText(_translate("CharacterSheet", "-"))
        self.hpPlusBtn.setText(_translate("CharacterSheet", "+"))
        self.groupBox_9.setTitle(_translate("CharacterSheet", "Hit Dice"))
        self.hitLbl.setText(_translate("CharacterSheet", "0"))
        self.groupBox_10.setTitle(_translate("CharacterSheet", "Death Saves"))
        self.deathLbl.setText(_translate("CharacterSheet", "0 : 0"))
        self.groupBox_11.setTitle(_translate("CharacterSheet", "Speed"))
        self.speedLbl.setText(_translate("CharacterSheet", "0"))
        self.groupBox_12.setTitle(_translate("CharacterSheet", "Weapons"))
        self.groupBox_13.setTitle(_translate("CharacterSheet", "Name"))
        self.weapon1Lbl.setText(_translate("CharacterSheet", "None"))
        self.weapon2Lbl.setText(_translate("CharacterSheet", "None"))
        self.weapon3Lbl.setText(_translate("CharacterSheet", "None"))
        self.groupBox_14.setTitle(_translate("CharacterSheet", "Bonus"))
        self.bonus1Lbl.setText(_translate("CharacterSheet", "None"))
        self.bonus2Lbl.setText(_translate("CharacterSheet", "None"))
        self.bonus3Lbl.setText(_translate("CharacterSheet", "None"))
        self.groupBox_15.setTitle(_translate("CharacterSheet", "Damage"))
        self.damage1Lbl.setText(_translate("CharacterSheet", "None"))
        self.damage2Lbl.setText(_translate("CharacterSheet", "None"))
        self.damage3Lbl.setText(_translate("CharacterSheet", "None"))
        self.groupBox_16.setTitle(_translate("CharacterSheet", "Proficiencies and Languages"))
        self.proficienciesLbl.setText(_translate("CharacterSheet", "None"))
        self.groupBox_17.setTitle(_translate("CharacterSheet", "Character Info"))
        self.groupBox_20.setTitle(_translate("CharacterSheet", "Personality Traits"))
        self.personalityLbl.setText(_translate("CharacterSheet", "None"))
        self.groupBox_21.setTitle(_translate("CharacterSheet", "Ideals"))
        self.idealsLbl.setText(_translate("CharacterSheet", "None"))
        self.groupBox_19.setTitle(_translate("CharacterSheet", "Flaws"))
        self.flawsLbl.setText(_translate("CharacterSheet", "None"))
        self.groupBox_18.setTitle(_translate("CharacterSheet", "Bonds"))
        self.bondsLbl.setText(_translate("CharacterSheet", "None"))
        self.spellBtn.setText(_translate("CharacterSheet", "Spells"))
        self.invBtn.setText(_translate("CharacterSheet", "Inventory"))
        self.editBtn.setText(_translate("CharacterSheet", "Edit"))
        self.groupBox_22.setTitle(_translate("CharacterSheet", "Feats and Traits"))
        self.groupBox_23.setTitle(_translate("CharacterSheet", "Feats"))
        self.featsLbl.setText(_translate("CharacterSheet", "None"))
        self.groupBox_24.setTitle(_translate("CharacterSheet", "Race Traits"))
        self.raceTraitsLbl.setText(_translate("CharacterSheet", "None"))
        self.groupBox_25.setTitle(_translate("CharacterSheet", "Background Traits"))
        self.backgroundTraitsLbl.setText(_translate("CharacterSheet", "None"))
        self.groupBox_26.setTitle(_translate("CharacterSheet", "Class Traits"))
        self.classTraitsLbl.setText(_translate("CharacterSheet", "None"))
        self.groupBox_27.setTitle(_translate("CharacterSheet", "Passive Wisdom"))
        self.pasWisdomLbl.setText(_translate("CharacterSheet", "0"))
        self.d.setText(_translate("CharacterSheet", "0"))
        self.f.setText(_translate("CharacterSheet", "0"))
        self.b.setText(_translate("CharacterSheet", "0"))
        self.h.setText(_translate("CharacterSheet", "0"))
        self.c.setText(_translate("CharacterSheet", "0"))
        self.j.setText(_translate("CharacterSheet", "0"))
        self.a.setText(_translate("CharacterSheet", "0"))
        self.e.setText(_translate("CharacterSheet", "0"))
        self.g.setText(_translate("CharacterSheet", "0"))
        self.i.setText(_translate("CharacterSheet", "0"))
        self.k.setText(_translate("CharacterSheet", "0"))
        self.l.setText(_translate("CharacterSheet", "0"))
        self.m.setText(_translate("CharacterSheet", "0"))
        self.p.setText(_translate("CharacterSheet", "0"))
        self.o.setText(_translate("CharacterSheet", "0"))
        self.n.setText(_translate("CharacterSheet", "0"))
        self.w.setText(_translate("CharacterSheet", "0"))
        self.x.setText(_translate("CharacterSheet", "0"))
        self.q.setText(_translate("CharacterSheet", "0"))
        self.v.setText(_translate("CharacterSheet", "0"))
        self.r.setText(_translate("CharacterSheet", "0"))
        self.s.setText(_translate("CharacterSheet", "0"))
        self.u.setText(_translate("CharacterSheet", "0"))
        self.label_24.setText(_translate("CharacterSheet", "Strength Saving Throw"))
        self.t.setText(_translate("CharacterSheet", "0"))
        self.label_48.setText(_translate("CharacterSheet", "Athletics"))
        self.label_49.setText(_translate("CharacterSheet", "Dexterity Saving Throw"))
        self.label_50.setText(_translate("CharacterSheet", "Acrobatics"))
        self.label_51.setText(_translate("CharacterSheet", "Sleight of Hand"))
        self.label_52.setText(_translate("CharacterSheet", "Stealth"))
        self.label_53.setText(_translate("CharacterSheet", "Constitution Saving Throw"))
        self.label_54.setText(_translate("CharacterSheet", "Intelligence Saving Throw"))
        self.label_55.setText(_translate("CharacterSheet", "Arcana"))
        self.label_56.setText(_translate("CharacterSheet", "History"))
        self.label_57.setText(_translate("CharacterSheet", "Investigation"))
        self.label_58.setText(_translate("CharacterSheet", "Nature"))
        self.label_59.setText(_translate("CharacterSheet", "Religeon"))
        self.label_60.setText(_translate("CharacterSheet", "Wisdom Saving Throw"))
        self.label_61.setText(_translate("CharacterSheet", "Animal Handling"))
        self.label_62.setText(_translate("CharacterSheet", "Insight"))
        self.label_63.setText(_translate("CharacterSheet", "Medicine"))
        self.label_64.setText(_translate("CharacterSheet", "Perception"))
        self.label_65.setText(_translate("CharacterSheet", "Survival"))
        self.label_66.setText(_translate("CharacterSheet", "Charisma Saving Throw"))
        self.label_67.setText(_translate("CharacterSheet", "Deception"))
        self.label_68.setText(_translate("CharacterSheet", "Intimidation"))
        self.label_69.setText(_translate("CharacterSheet", "Performance"))
        self.label_70.setText(_translate("CharacterSheet", "Persuasion"))
        self.loadBtn.setText(_translate("CharacterSheet", "New / Load"))

